apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port | default 3306 }}
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
status:
  loadBalancer: {}