apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: todo-stage
  namespace: monitoring
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - todo-stage
  selector:
    matchLabels:
      app: todo-app