apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  source:
    path: k8s/tests
    repoURL: https://github.com/yp3yp3/Todo_list-cd
    targetRevision: HEAD
    directory:
      include: nginx.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
