apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.10.0
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.yp3yp3.site
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.yp3yp3.site
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - alertmanager.yp3yp3.site
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
