apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.10.0  
    helm:
      values: |
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - grafana.yp3yp3.site

        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - prometheus.yp3yp3.site

        alertmanager:
          config:
            global:
              resolve_timeout: 5m
            route:
              receiver: 'slack-notifications'
            receivers:
              - name: 'slack-notifications'
                slack_configs:
                  - api_url: 'https://hooks.slack.com/services/T12345678/B12345678/AbcDefGhIjKlMnOpQrStUv'
                    channel: '#alerts'
                    send_resolved: true
                    title: '{{ .CommonAnnotations.summary }}'
                    text: '{{ .CommonAnnotations.description }}'
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - alertmanager.yp3yp3.site
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    CreateNamespace: true
