apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-addons
  namespace: argocd
spec:
  destination:
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: k8s/prometheus
    repoURL: https://github.com/yp3yp3/Todo_list-cd
    targetRevision: HEAD
    directory:
      recurse: true
  dependencies:
    - prometheus
  sources: []
  project: ''
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
