    - name: run app container
      docker_container:
        name: app
        image: "{{ app_image }}:{{ app_tag }}"
        restart_policy: always
        env:
          DB_NAME: "{{ db_name }}"
          DB_USER: "{{ db_user }}"
          DB_PASSWORD: "{{ db_password }}"
          DB_HOST: "{{ db_host }}"
        ports: "5000:5000"
