apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0.7giga
spec:
  capacity:
    storage: 700Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pv2 
