apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: todo
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  - host: {{ .Values.ingress.app_host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.app.Service.name }}
            port:
              number: {{ .Values.app.Service.port }}
        path: /
        pathType: Prefix
status:
  loadBalancer: {}