    - name: install docker
      apt:
        name:
          - docker.io
        update_cache: yes

    - name: Add ubuntu user to docker group
      user:
          name: "{{ ansible_user }}"
          groups: docker
          append: yes
